exports.REGISTER_EMAIL_INVALID = 1

exports.REGISTER_PASSWORD_INVALID = 2

exports.REGISTER_USER_INVALID = 3

exports.LOGING_USER_INVALID = 4

exports.LOGING_PASSWORD_FORMAT_INVALID = 5

exports.LOGING_PASSWORD_INVALID = 6

exports.LOGING_NO_ACTIVE = 7

exports.LOGIN_EMAIL_INVALID = 8

exports.DATA_FORMAT_INVALID = 10;

exports.USER_INVALID = 11;

exports.REQUEST_INVALID_COST = 12;

exports.LACK_BALANCE = 13;


exports.VERIFY_EMAIL = 15;

exports.UNKNOWN = 14;


